apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vue-statics.fullname" . }}
  labels:
    {{- include "vue-statics.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "vue-statics.selectorLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "vue-statics.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "vue-statics.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Release.Name }}
          env:
            {{- if and (not .Values.envVars) (not .Values.logCollector.enabled) }}
            {}
            {{- else }}
            {{- range $key, $val := .Values.envVars }}
            - name: {{ $key }}
              value: {{ $val }}
            {{- end }}
            {{- if .Values.logCollector.enabled }}
            {{- if .Values.logCollector.logfile }}
            - name: aliyun_logs_{{ .Release.Name }}
              value: {{ .Values.logCollector.logfile }}
            {{- end }}
            - name: aliyun_logs_{{ .Release.Name }}-stdout
              value: stdout
            {{- end }}
            {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 5"]
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: tz-shanghai
              mountPath: /etc/localtime
            - name: volumn-sls-dir
              mountPath: /app/logs
      volumes:
        - name: volumn-sls-dir
          emptyDir: {}
        - name: tz-shanghai
          hostPath:
            path: /etc/localtime
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
