ingress:
  enabled: true
  annotations: {kubernetes.io/ingress.class: nginx}
  hostPath: /
  hostRepo: repo.demo
  hostDocker: registry.demo

nexus:
  env:
    - name: NEXUS_SECURITY_RANDOMPASSWORD
      value: "false"
  dockerSupport:
    enabled: true