apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nodejs.fullname" . }}
  labels:
    {{- include "nodejs.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nodejs.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nodejs.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "nodejs.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Release.Name }}
          env:
            - name: TZ
              value: Asia/Shanghai
            {{- if .Values.envVars -}}
            {{- range $key, $val := .Values.envVars }}
            - name: {{ $key }}
              value: {{ $val }}
            {{- end -}}
            {{- end -}}
            {{- if .Values.logCollector.enabled -}}
            {{- if .Values.logCollector.logfile }}
            - name: aliyun_logs_{{ .Release.Name }}
              value: {{ .Values.logCollector.logfile | quote }}
            {{- end }}
            - name: aliyun_logs_{{ .Release.Name }}-stdout
              value: stdout
            {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 5"]
          ports:
            - name: http
              containerPort: {{ .Values.listenPort | default 80 }}
              protocol: TCP
          livenessProbe:
            {{- if eq .Values.healthCheck.liveness.method "httpGet" }}
            httpGet:
              path: {{ .Values.healthCheck.liveness.path | default "/" }}
              port: http
            {{- end }}
            failureThreshold: 5
            initialDelaySeconds: 30
            periodSeconds: 6
            successThreshold: 1
            timeoutSeconds: 3
          readinessProbe:
            {{- if eq .Values.healthCheck.readiness.method "httpGet" }}
            httpGet:
              path: {{ .Values.healthCheck.readiness.path | default "/" }}
              port: http
            {{- end }}
            failureThreshold: 7
            initialDelaySeconds: 25
            periodSeconds: 6
            successThreshold: 2
            timeoutSeconds: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: tz-shanghai
              mountPath: /etc/localtime
            - name: volumn-sls-dir
              mountPath: /app/logs
      volumes:
        - name: volumn-sls-dir
          emptyDir: {}
        - name: tz-shanghai
          hostPath:
            path: /etc/localtime
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
