apiVersion: v1
kind: Service
metadata:
  name: {{ include "nodejs.fullname" . }}
  labels:
    {{- include "nodejs.labels" . | nindent 4 }}
  annotations:
    {{- if eq .Values.service.type "LoadBalancer" }}
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-address-type: {{ .Values.service.lbAddressType | default "intranet"}}
    {{- end }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default "80" }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "nodejs.selectorLabels" . | nindent 4 }}
