---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-ali-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: alicloud-disk-essd
  resources:
    requests:
      storage: 35Gi


