apiVersion: log.alibabacloud.com/v1alpha1
kind: AliyunLogConfig
metadata:
  # your config name, must be unique in you k8s cluster
  name: istio-proxy-access-log
spec:
  # logstore name to upload log
  logstore: accesslogs
  # logtail config detail
  logtailConfig:
    # log file's input type is 'file'
    inputType: plugin
    # logtail config name, should be same with [metadata.name]
    configName: istio-proxy-access-log
    inputDetail:
      plugin:
        inputs:
          - type: service_docker_stdout
            # input type
            detail:
              # collect stdout and stderr
              Stdout: true
              Stderr: false
              IncludeEnv:
                ISTIO_META_CLUSTER_ID: Kubernetes
