apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: roxe.io-tls-secret
spec:
  secretName: roxe.io-tls-secret
  issuerRef:
    name: cert-manager-webhook-dnspod-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: '*.roxe.io'
  dnsNames:
    - roxe.io
    - "*.roxe.io"
