apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: roxepro.top-tls-secret
spec:
  secretName: roxepro.top-tls-secret
  issuerRef:
    name: cert-manager-webhook-dnspod-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: '*.roxepro.top'
  dnsNames:
    - roxepro.top
    - "*.roxepro.top"
