apiVersion: v2
name: nexus-iq-server

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 121.0.0
# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 1.121.0

description: Sonatype Nexus IQ Server continuously monitors your entire software supply chain

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

keywords:
  - sonatype
  - nexus
  - lifecycle
  - iq
  - remediate
  - vulnerabilities
  - policy
home: https://www.sonatype.com/product-nexus-lifecycle
icon: https://sonatype.github.io/helm3-charts/NexusIQServer_Vertical.svg
maintainers:
  - email:  support@sonatype.com
    name: Sonatype
