# Default values for iqserver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
statefulset:
  # This is not supported
  enabled: false
replicaCount: 1
image:
  # Sonatype Official Public Image
  repository: sonatype/nexus-iq-server
  tag: 1.121.0
  pullPolicy: IfNotPresent
  
iq:
  name: nxiq
  hostname: iq-server.demo
  applicationPort: 8070
  adminPort: 8071
  memory: 1Gi
  # base 64 encoded license file with no line breaks
  licenseSecret: ""
  # add this line with this file path and the `licenseSecret` above to autoconfigure licensing
  # licenseFile: /etc/nexus-iq-license/license_lic
  extraLabels:
  # add the following two lines to mount a secrets volume within the container at the specified location  
  secretName: #secret-jks
  secretMountName: #/etc/secret-volume
  env:
    - name: JAVA_OPTS
      value: "-Djava.util.prefs.userRoot=${SONATYPE_WORK}/javaprefs"
      
# In conjunction with 'secretName' and 'secretMountName' above, this is an example of how to inject required password
# secrets into the runtime environment, and how to modify the startup of the server to utilize custom Java SSL stores.
#    - name: TRUSTSTORE_PASSWORD
#        valueFrom:
#          secretKeyRef:
#            name: secret-jks
#            key: truststorePassword
#    - name: KEYSTORE_PASSWORD
#      valueFrom:
#        secretKeyRef:
#          name: secret-jks
#          key: keystorePassword
#    - name: JAVA_OPTS
#      value: "-Djavax.net.ssl.keyStoreType=jks -Djavax.net.ssl.keyStore=/etc/secret-volume/keystore.jks -Djavax.net.ssl.keyStorePassword=$(KEYSTORE_PASSWORD) -Djavax.net.ssl.trustStoreType=jks -Djavax.net.ssl.trustStore=/etc/secret-volume/truststore.jks -Djavax.net.ssl.trustStorePassword=$(TRUSTSTORE_PASSWORD) -Djava.util.prefs.userRoot=${SONATYPE_WORK}/javaprefs"


deploymentStrategy: Recreate
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: "ClusterIP"
  port: 80

ingress:
  enabled: false
  annotations: {kubernetes.io/ingress.class: nginx}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hostUI: iq-server.demo
  hostUIPath: /
  hostAdmin: admin.iq-server.demo
  hostAdminPath: /

  tls: []
    # - secretName: nexus-local-tls
    #   hosts:
    #     - iqserver.local
    #     - admin.iqserver.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  ## If defined, storageClass: <storageClass>
  ## If set to "-", storageClass: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClass spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  # storageClass: "-"
  storageSize: 1Gi
  # existingClaim:
  # annotations:
  #  "helm.sh/resource-policy": keep
  # storageClass: "-"
  # volumeConfiguration:
  #   hostPath:
  #     path: /data/nxiq/
  # If you want to use existing PersistentDisk with data, you can create a PV for it by uncommenting the following lines. (Currently supports GCE PD only)
  # pdName: nexus-data-disk
  # fsType: ext4
  # Uncomment below 2 lines, if you want to use an existing GCE PersistentDisk for IQ Logs.
  # logpdName: nexus-log-disk
  # logfsType: ext4

# configYaml is the full text of the config.yml file that will be passed to IQ Server
configYaml:
  baseUrl: http://iq-server.demo
  sonatypeWork: /sonatype-work
  server:
    applicationConnectors:
      - type: http
        port: 8070
    adminConnectors:
      - type: http
        port: 8071
    # HTTP request log settings.
    requestLog: 
      appenders:
        #All appenders set to console
        - type: file
          currentLogFilename: /var/log/nexus-iq-server/request.log    
          # Do not display log statements below this threshold to stdout.
          # threshold: INFO
          logFormat: "%clientHost %l %user [%date] \"%requestURL\" %statusCode %bytesSent %elapsedTime \"%header{User-Agent}\""
          archivedLogFilenamePattern: /var/log/nexus-iq-server/request-%d.log.gz
          archivedFileCount: 50
  
  createSampleData: true

  logging:

    # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
    level: DEBUG

    # Logger-specific settings.
    loggers:
      "com.sonatype.insight.scan": INFO
      "eu.medsea.mimeutil.MimeUtil2": INFO
      "org.apache.http": INFO
      "org.apache.http.wire": ERROR
      "org.eclipse.birt.report.engine.layout.pdf.font.FontConfigReader": WARN
      "org.eclipse.jetty": INFO
      "org.apache.shiro.web.filter.authc.BasicHttpAuthenticationFilter": INFO   # WARNING: This reveals credentials at DEBUG level
      "com.sonatype.insight.audit":
        appenders:
          #All appenders set to console
          - type: file
            currentLogFilename: /var/log/nexus-iq-server/audit.log    
            # Do not display log statements below this threshold to stdout.
            # threshold: INFO
            archivedLogFilenamePattern: /var/log/nexus-iq-server/audit-%d.log.gz
            archivedFileCount: 50

      "com.sonatype.insight.policy.violation":
        appenders:
          - type: console
    
            # Do not display log statements below this threshold to stdout.
            threshold: INFO

    appenders:
  
      # Settings for logging to stdout.
      - type: console
    
        # Do not display log statements below this threshold to stdout.
        threshold: INFO
      
        logFormat: "%d{'yyyy-MM-dd HH:mm:ss,SSSZ'} %level [%thread] %X{username} %logger - %msg%n"

      - type: file
    
        # Do not display log statements below this threshold to stdout.
        threshold: ALL
      
        logFormat: "%d{'yyyy-MM-dd HH:mm:ss,SSSZ'} %level [%thread] %X{username} %logger - %msg%n"
        # The file to which current statements will be logged.
        currentLogFilename: /var/log/nexus-iq-server/clm-server.log
        archivedLogFilenamePattern: /var/log/nexus-iq-server/clm-server-%d.log.gz
        archivedFileCount: 50


